;;(package-initialize)

(add-to-list 'load-path "~/.emacs.d/lisp/")
(normal-top-level-add-subdirs-to-load-path)
;; ----------------------------------------包管理.放最上面
(require 'init-packages)
(require 'init-evil)
(require 'init-better-defaults)
(require 'init-scheme)
(require 'init-kbd-macros)
(require 'init-save)
(require 'init-vc)
(require 'init-query-replace)
(require 'init-input)
(require 'init-org)
(require 'init-open-file)
