(defun open-init-file()
  (interactive)
  (setq-default display-line-numbers 'relative)
  (find-file "~/.emacs.d/init.el"))
(defun find-emacs-lisp-file(relative-path)
  (interactive)
  (find-file (concat "~/.emacs.d/lisp/" relative-path)))

(defun open-init-packages()
  (interactive)
  (find-emacs-lisp-file "init-packages.el"))
(defun open-init-better-defaults()
  (interactive)
  (find-emacs-lisp-file "init-better-defaults.el"))
(defun open-init-evil()
  (interactive)
  (find-emacs-lisp-file "init-evil.el"))
(defun open-init-scheme()
  (interactive)
  (find-emacs-lisp-file "init-scheme.el"))
(defun open-init-kbd-macros()
  (interactive)
  (find-emacs-lisp-file "init-kbd-macros.el"))
(defun open-init-base()
  (interactive)
  (find-emacs-lisp-file "init-base.el"))
(defun open-init-save()
  (interactive)
  (find-emacs-lisp-file "init-save.el"))
(defun open-init-git()
  (interactive)
  (find-emacs-lisp-file "init-git.el"))
(defun open-init-abbrev()
  (interactive)
  (find-emacs-lisp-file "init-abbrev.el"))
(defun open-init-rime()
  (interactive)
  (find-emacs-lisp-file "init-rime.el"))
(defun open-init-open-file()
  (interactive)
  (find-emacs-lisp-file "init-open-file.el"))


(provide 'init-open-file)
